name: PullRequest
on: [pull_request]
jobs:
  PullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run tests
        run: npm run test && npm run test:unit
      - name: Build
        run: npm i && npm run build